### ISSUE TITLE
[C-17] Ration Bug

### ISSUE THREAD

**Issue by XenServa** [nulleve/TR-Community#5]
**Describing the Bug**
A Clear and Concise Description of what the Bug is
1. An Action that you did;
     Gave a GRID unit a drink
2. A Description of How it occured.
I gave a GRID unit a drink from the vending machine while in IS morph and then attempted to frisk a citizen, the "give ration" prompt began popping up for everyone when in proximity despite having no tool in hand and frisk does not work when you attempt to use it.
    

**To Reproduce**
To the Best of your ability, list either the Confirmed steps, or up to 10 of the Last things you had done, e.g:
1. Gave drink to GRID unit
2. Attempted to frisk a citizen
3. Give ration prompt pops up when in proximity of anyone despite having no tool in hand

1. Individual Information
    - Windows Users;
        - OS `*`: Windows 10
        
2. Roblox Information
    - Roblox Graphics Level 1

**Comment by nulleve** [comment]
@GithubPagesStuff Do you think this is being caused because of [the change from this Commit](https://github.com/nulleve/TR-Public/blob/32c5ea048634ae825db7650994b1241d3d1255a2/City/src/ServerScriptService/Handlers/RationsHandler.server.lua#L86-L117), PR [#20](https://github.com/nulleve/TR-Public/commit/46bc3ab8f5938c6284a90205b7e5070cd749340d)

**Comment by nulleve** [comment]
Closing, fixed in https://github.com/nulleve/TR-Public/pull/70. Will be in the latest publish.
